name: Build Windows Installer with PyInstaller

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Build EXE and Installer for Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |    
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install NSIS
        run: |
          choco install nsis -y
          refreshenv

      - name: Build EXE with PyInstaller
        run: |
          python -m PyInstaller --onefile --hidden-import=aiomysql --name RetailHub main.py
          
          if (!(Test-Path "dist/RetailHub.exe")) {
            echo "Error: dist/RetailHub.exe not found"
            dir "dist"  # 列出dist目录内容
            exit 1
          }


      - name: Debug information
        run: |    
          echo "Current directory contents:"
          dir
          echo "Dist directory contents:"
          dir "dist"

      - name: Create installer with NSIS
        run: |
          if (!(Test-Path "dist/RetailHub.exe")) {
            echo "Error: dist/RetailHub.exe not found, cannot create installer"
            exit 1
          }
          # 创建安装脚本
          echo 'Name "RetailHub"' > installer.nsi
          echo 'OutFile "dist/RetailHub-Installer.exe"' >> installer.nsi
          echo 'InstallDir $PROGRAMFILES\RetailHub' >> installer.nsi
          echo 'Section' >> installer.nsi
          echo '  SetOutPath $INSTDIR' >> installer.nsi
          echo '  File "dist/RetailHub.exe"' >> installer.nsi
          echo '  WriteUninstaller "$INSTDIR\uninstall.exe"' >> installer.nsi
          echo 'SectionEnd' >> installer.nsi
          echo 'Section "Uninstall"' >> installer.nsi
          echo '  Delete "$INSTDIR\RetailHub.exe"' >> installer.nsi
          echo '  Delete "$INSTDIR\uninstall.exe"' >> installer.nsi
          echo '  RMDir "$INSTDIR"' >> installer.nsi
          echo 'SectionEnd' >> installer.nsi
          & "C:\Program Files (x86)\NSIS\makensis.exe" installer.nsi

      - name: Archive installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: RetailHub-installer
          path: dist/RetailHub-Installer.exe
