name: Build Windows Installer with PyInstaller

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    name: Build EXE and Installer for Windows

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up NSIS
        uses: joncloud/makensis-action@v4.1

      - name: Install dependencies
        run: |    
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          python -m PyInstaller --onefile --hidden-import=aiomysql --name retailhub main.py

      - name: Create installer with NSIS
        run: |
          # 创建安装脚本
          echo 'Name "RetailHub"' > installer.nsi
          echo 'OutFile "dist/RetailHub-Installer.exe"' >> installer.nsi
          echo 'InstallDir $PROGRAMFILES\RetailHub' >> installer.nsi
          echo 'Section' >> installer.nsi
          echo '  SetOutPath $INSTDIR' >> installer.nsi
          echo '  File "dist/retailhub.exe"' >> installer.nsi
          echo '  WriteUninstaller "$INSTDIR\uninstall.exe"' >> installer.nsi
          echo 'SectionEnd' >> installer.nsi
          echo 'Section "Uninstall"' >> installer.nsi
          echo '  Delete "$INSTDIR\retailhub.exe"' >> installer.nsi
          echo '  Delete "$INSTDIR\uninstall.exe"' >> installer.nsi
          echo '  RMDir "$INSTDIR"' >> installer.nsi
          echo 'SectionEnd' >> installer.nsi
          makensis installer.nsi

      - name: Archive installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: retailhub-installer
          path: dist/RetailHub-Installer.exe
